### PR TITLE
Add $additionalParameters

### PR DESCRIPTION
**Pull request by MJECloud**
Allow to use own additionalParameters 
See here: https://github.com/kine/MSDyn365BC_AppTemplate/pull/5

### CODE REVIEW

**Comment by kine** [comment]
Thanks, but I will preffer way, where the additional parameters in the functions are dynamically created from custom additional parameters and the one already used. This will allow to define only new custom parameters in the settings.ps1. Or do you need to have way to overload even these? I mean mainly the --volume ""$($RepoPath):C:\app" which is critical for other functions to be there. Rest could be optional and e.g. used as "default" if not defined from outside.

**Comment by MJECloud** [comment]
You're right it would be better adding optional parameters to the mandatory. 
I'll change that.

**Comment by MJECloud** [comment]
Now you can specifiy optionalParameters array. This will added to the additionalParameters array

**Comment by kine** [comment]
Get-ALAppOrder is missing line 
`[CMDLetBinding(DefaultParameterSetName="Path")]`
Is it mistake or it should not be there? This was fixed by some previous PR...

**Comment by MJECloud** [comment]
Thank you, it was a mistake.
I fixed it.

**Comment by kine** [comment]
Thanks! Merged. Will be included in next version.

**Pull request merged**
