### PR TITLE
Support for conditionally including c/side such that >=v15 can be cre…

### PR DESCRIPTION
**Pull request by kfuglsang**
…ated

### CODE REVIEW

**Comment by kine** [comment]
Thanks. I am thinking about adding parameter as any other, like [bool]IncludeCSide=$true and you will be able to set it like other values from the settings or as parameter. This will allow to set it in the settings file you could have in the repositories etc. What do you think?

**Comment by kfuglsang** [comment]
Yeah, that sounds fine.

**Comment by kine** [comment]
Published in v0.9.84

**Comment by kfuglsang** [comment]
Added support for v15 using "BC" as serverinstance name.

**Comment by kine** [comment]
Published in v0.9.85

**Pull request merged**
