### PR TITLE
Update Compile-ALProjectTree.ps1

### PR DESCRIPTION
**Pull request by MJECloud**
Added check if signtool is available else throw exception.
Use full signtool path instead of system32 shortcut.

### CODE REVIEW

**Comment by kine** [comment]
Thanks! I am now using in Azure DevOps the Sign-NAVContainerApp from navcontainerhelper. I recommend to use it too. I will try to update the script to use the container to sign the app if possible to prevent need of installing the SDK.

**Comment by kine** [comment]
I moved the code into the if block to test the path only if $CertPath is set and thus the tool will be used.

**Comment by MJECloud** [comment]
Hello Kamil, 

thanks for your quick response. 
You say that you already use Sign-NAVContainerApp. Do you know when you will publish that in your Code? 
Otherwise i can edit the module, if its ok. 

Greetings,
Maurice

**Comment by kine** [comment]
I have just published new version. If CertPath and CertPwd is filled in, the app is signed in container. If only CertPath is filled (no CertPwd - this means that it will use account permissions inside the certificate - new windows allows you to set permissions for domain accounts in the certificate) the app is signed on host, because navcontianerhelper does not support this (it is out of domain). Not yet tested...

**Comment by MJECloud** [comment]
Thank you! I'll give it a try today.

**Pull request merged**
